version: 1.0.{build}
configuration: Debug
platform: Any CPU
cache: packages -> **\packages.config

before_build:
- cmd: nuget restore DangrLib.sln

build:
  project: DangrLib.sln
  parallel: true
  verbosity: minimal

test_script:
- ps: .\build\CodeCoverage.ps1

after_test:
 - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
 - pip install codecov
 - codecov -f "DangrLib_coverage.xml"

notifications:
- provider: Email
  to:
  - dangerdan9631@live.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
