# https://docs.codecov.io/docs/codecov-yaml#section-default-yaml
codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "65...85"

  status:
    project:
      default:
        enabled: yes
        target: auto
        threshold: 1
    patch:
      default:
        enabled: yes
        target: 85%
    changes: no

  parsers:
    gcov:
      branch_detection:
        conditional: yes
        loop: yes
        method: yes
        macro: no

comment:
  layout: "header, diff, changes, sunburst, suggestions, tree"
  behavior: new